# Custom Language File for Launcher Customizer

[ejs.app]
title = "페스티벌 런쳐"

[ejs.landing]
mediaGitHubURL = "https://github.com/IPECTER"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/RTUServer/FestivalLauncher"
supportLink = "https://toss.me/ipecter"

[ejs.welcome]
welcomeHeader = "페스티벌에 오신 것을 환영합니다!"
welcomeDescription = "페스티벌은 모든 크리에이터분들이<br>힐링 마인크래프트를 편하게 즐길 수 있도록 갖춰진 곳입니다!"
welcomeDescCTA = "<b>시작하기</b>를 눌러 당신의 여정을 떠나보세요!"