[ejs.landing]
updateAvailableTooltip = "새로운 업데이트 대기중"
usernamePlaceholder = "닉네임"
usernameEditButton = "수정"
settingsTooltip = "설정"
serverStatus = "서버"
serverStatusPlaceholder = "오프라인"
mojangStatus = "모장"
mojangStatusTooltipTitle = "서비스 목록"
mojangStatusNETitle = "기&nbsp;타"
newsButton = "공지사항"
launchButton = "플레이"
launchButtonPlaceholder = "&#8226; 서버가 선택되지 않았습니다."
launchDetails = "잠시만 기다려주세요.."
newsNavigationStatus = "{currentPage} / {totalPages}"
newsErrorLoadSpan = "새로운 공지를 확인하고 있습니다.."
newsErrorFailedSpan = "공지를 불러오는 데 실패하였습니다."
newsErrorRetryButton = "재시도"
newsErrorNoneSpan = "공지가 없습니다."

[ejs.login]
loginCancelText = "취소"
loginSubheader = "마인크래프트 로그인"
loginEmailError = "* 잘못된 값"
loginEmailPlaceholder = "이메일 또는 닉네임"
loginPasswordError = "* 필수"
loginPasswordPlaceholder = "비밀번호"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "암호 찾기"
loginRememberMeText = "로그인 상태 유지"
loginButtonText = "로그인"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "계정 생성"
loginPasswordDisclaimer1 = "비밀번호는 저장되지 않으며 Mojang 인증 서버에 직접 전송됩니다."
loginPasswordDisclaimer2 = "{appName}는 Mojang AB와는 관련 없는 프로그램입니다."

[ejs.loginOptions]
loginOptionsTitle = "로그인 옵션"
loginWithMicrosoft = "마이크로소프트 로그인"
loginWithMojang = "모장 로그인"
cancelButton = "취소"

[ejs.overlay]
serverSelectHeader = "사용 가능한 서버"
serverSelectConfirm = "선택"
serverSelectCancel = "취소"
accountSelectHeader = "계정 선택"
accountSelectConfirm = "선택"
accountSelectCancel = "취소"

[ejs.settings]
navHeaderText = "설정"
navAccount = "계정"
navMinecraft = "마인크래프트"
navMods = "모드"
navJava = "자바"
navLauncher = "런쳐"
navAbout = "정보"
navUpdates = "업데이트"
navDone = "완료"
tabAccountHeaderText = "계정 설정"
tabAccountHeaderDesc = "계정을 추가하거나 관리합니다."
microsoftAccount = "마이크로소프트"
addMicrosoftAccount = "+ 새로운 마이크로소프트 계정"
mojangAccount = "모장"
addMojangAccount = "+ 새로운 모장 계정"
minecraftTabHeaderText = "마인크래프트 설정"
minecraftTabHeaderDesc = "실행 옵션"
gameResolutionTitle = "해상도"
launchFullscreenTitle = "전체화면"
autoConnectTitle = "서버 자동 연결"
launchDetachedTitle = "런쳐 실행 유지"
launchDetachedDesc = "게임이 시작될때 런쳐를 종료하지 않고 유지합니다."
tabModsHeaderText = "모드"
tabModsHeaderDesc = "모드를 활성화하거나 비활성화합니다."
switchServerButton = "변경"
requiredMods = "필수 모드"
optionalMods = "선택 모드"
dropinMods = "추가 모드"
addMods = "모드 추가하기"
dropinRefreshNote = "(F5 새로고침)"
shaderpacks = "쉐이더팩"
shaderpackDesc = "쉐이더를 활성화하거나 비활성화합니다. 추가 및 선택할 수 있습니다."
selectShaderpack = "쉐이더 선택"
tabJavaHeaderText = "자바 설정"
tabJavaHeaderDesc = "자바 관련 설정을 조정합니다. (고급)"
memoryTitle = "메모리"
maxRAM = "최대 메모리"
minRAM = "최소 메모리"
memoryDesc = "최소 4기가의 메모리를 추천합니다. 또한 최소 메모리와 최대 메모리를 같은 값으로 설정하면 성능 향상에 도움이 될 수 있습니다."
memoryTotalTitle = "전체"
memoryAvailableTitle = "사용 가능"
javaExecutableTitle = "자바 런타임"
javaExecSelDialogTitle = "자바 런타임을 선택합니다."
javaExecSelButtonText = "파일 선택"
javaExecDesc = "실행 전 자바 런타임을 검증합니다. Java 17 이상의 x64 런타임이 필요합니다."
javaPathDesc = "경로는 <strong>{pathSuffix}</strong>로 끝나야합니다."
jvmOptsTitle = "추가 JVM 옵션"
jvmOptsDesc = "JVM 적용 옵션입니다 <em>-Xms</em>와 <em>-Xmx</em>는 추가되지 않아야합니다."
launcherTabHeaderText = "런쳐 설정"
launcherTabHeaderDesc = "런쳐와 관련된 설정을 조정합니다."
allowPrereleaseTitle = "베타 버전 사용하기"
allowPrereleaseDesc = "새로운 기능이 탑재된 버전을 사용합니다. 그러나 검증되지 않은 일부 문제가 발생할 수도 있습니다."
dataDirectoryTitle = "데이터 폴더"
selectDataDirectory = "데이터 폴더 선택"
chooseFolder = "폴더 선택"
dataDirectoryDesc = "모든 게임 파일과 자동 설치된 자바는 이곳에 저장됩니다.<br>스크린샷과 월드는 하위 폴더에 저장됩니다."
aboutTabHeaderText = "정보"
aboutTabHeaderDesc = "정보와 현재 버전에 대한 변경사항을 확인합니다."
aboutTitle = "{appName}"
stableRelease = "정식 버전"
versionText = "버전 "
sourceGithub = "깃허브"
support = "후원"
devToolsConsole = "개발 콘솔"
releaseNotes = "패치 노트"
changelog = "변경 사항"
noReleaseNotes = "패치 노트 없음"
viewReleaseNotes = "GitHub에서 패치노트 확인"
launcherUpdatesHeaderText = "런쳐 업데이트"
launcherUpdatesHeaderDesc = "다운로드, 업데이트, 패치 확인을 진행합니다."
checkForUpdates = "업데이트 확인"
whatsNew = "추가된 사항"
updateReleaseNotes = "패치 노트 확인"

[ejs.waiting]
waitingText = "마이크로소프트 응답 기다리는 중.."

[ejs.welcome]
continueButton = "시작하기"


[js.discord]
waiting = "클라이언트 기다리는 중.."
state = "서버: {shortId}"

[js.index]
microsoftLoginTitle = "마이크로소프트 로그인"
microsoftLogoutTitle = "마이크로소프트 로그아웃"

[js.login]
login = "로그인"
loggingIn = "로그인 중: "
success = "성공"
tryAgain = "재시도"

[js.login.error]
invalidValue = "* 잘못된 값"
requiredValue = "* 필수"

[js.login.error.unknown]
title = "Unknown Error During Login"
desc = "An unknown error has occurred. Please see the console for details."

[js.landing.launch]
pleaseWait = "잠시만 기다려주세요.."
failureTitle = "런쳐 로딩 중 오류가 발생하였습니다."
failureText = "See console (CTRL + Shift + i) for more details."
okay = "확인"

[js.landing.selectedAccount]
noAccountSelected = "계정 없음"

[js.landing.selectedServer]
noSelection = "서버가 선택되지 않음"
loading = "로딩 중.."

[js.landing.serverStatus]
server = "서버"
offline = "오프라인"
players = "플레이어"

[js.landing.systemScan]
checking = "시스템 정보 확인중.."
noCompatibleJava = "호환 가능한 자바 설치 없음"
installJavaMessage = "마인크래프트를 실행하기 위해선 Java {major} 이상의 x64 런타임이 필요합니다. 설치하시겠습니까?"
installJava = "자바 설치"
installJavaManually = "수동 설치"
javaDownloadPrepare = "자바 다운로드를 준비하는 중.."
javaDownloadFailureTitle = "자바 다운로드 중 오류 발생"
javaDownloadFailureText = "See console (CTRL + Shift + i) for more details."
javaRequired = "실행하려면 자바가 필요합니다"
javaRequiredMessage = '실행하려면 Java {major} 이상의 x64 런타임이 필요합니다.<br><br>이 <a href="https://youtu.be/x-Eg4GOTxBY?si=wIgyrJxk-BzRJcB4">영상</a>을 따라 설치해주세요.'
javaRequiredDismiss = "이해했습니다"
javaRequiredCancel = "뒤로가기"

[js.landing.downloadJava]
findJdkFailure = "자바 다운로드 불러오기에 실패하였습니다."
javaDownloadCorruptedError = "잘못된 파일 해쉬를 가지고 있습니다."
extractingJava = "자바 압축 해제 중"
javaInstalled = "자바 설치 완료!"

[js.landing.dlAsync]
loadingServerInfo = "서버 정보를 불러오는 중.."
fatalError = "심각한 오류 발생"
unableToLoadDistributionIndex = "Could not load a copy of the distribution index. See the console (CTRL + Shift + i) for more details."
pleaseWait = "잠시만 기다려주세요.."
errorDuringLaunchTitle = "실행 중 오류 발생"
seeConsoleForDetails = "See console (CTRL + Shift + i) for more details."
validatingFileIntegrity = "파일 무결성을 검증하는 중.."
errorDuringFileVerificationTitle = "파일 검증 중 오류 발생"
downloadingFiles = "파일 다운로드 중.."
errorDuringFileDownloadTitle = "파일 다운로드 중 오류 발생"
preparingToLaunch = "시작 준비 중.."
launchingGame = "게임을 시작하는 중.."
launchWrapperNotDownloaded = "LaunchWrapper가 다운로드 되지 않았습니다."
doneEnjoyServer = "페스티벌을 시작합니다!"
checkConsoleForDetails = "Please check the console (CTRL + Shift + i) for more details."

[js.landing.news]
checking = "Checking for News"

[js.landing.discord]
loading = "페스티벌을 즐기는 중!."
joining = "페스티벌을 즐기는 중!!"
joined = "페스티벌을 즐기는 중!!!"

[js.overlay]
dismiss = "취소"

[js.settings.fileSelectors]
executables = "실행 파일"
allFiles = "모든 파일"

[js.settings.mstfLogin]
errorTitle = "Something Went Wrong"
errorMessage = "Microsoft authentication failed. Please try again."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Something Went Wrong"
errorMessage = "Microsoft logout failed. Please try again."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "계정 선택"
selectedButton = "선택된 계정 &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "연동된 마지막 계정입니다."
lastAccountWarningMessage = "로그아웃하면 프로그램을 실행할 때 다시 로그인해야 합니다."
confirmButton = "확인"
cancelButton = "취소"

[js.settings.authAccountPopulate]
username = "닉네임"
uuid = "UUID"
selectAccount = "계정 선택"
selectedAccount = "선택된 계정 ✓"
logout = "로그아웃"

[js.settings.dropinMods]
removeButton = "제거"
deleteFailedTitle = "Failed to Delete<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Make sure the file is not in use and try again."
failedToggleTitle = "Failed to Toggle<br>One or More Drop-in Mods"
okButton = "Okay"

[js.settings.serverListing]
mainServer = "메인 서버"

[js.settings.java]
selectedJava = "자바: Java {version} ({vendor})"
invalidSelection = "잘못된 자바입니다."
requiresJava = "Java {major} x64 런타임이 필요합니다."
availableOptions = "Java {major}의 사용 가능한 옵션"

[js.settings.about]
preReleaseTitle = "베타 버전"
stableReleaseTitle = "정식 버전"
releaseNotesFailed = "패치 노트를 불러오는 데 실패하였습니다."

[js.settings.updates]
newReleaseTitle = "새로운 버전이 출시하였습니다."
newPreReleaseTitle = "새로운 베타 버전이 출시하였습니다."
downloadingButton = "다운로드 중.."
downloadButton = '다운로드 (런쳐를 종료 후 설치해야 합니다.)'
latestVersionTitle = "최신 버전을 사용하고 있습니다."
checkForUpdatesButton = "업데이트 확인"
checkingForUpdatesButton = "업데이트 확인 중.."

[js.uibinder.startup]
fatalErrorTitle = "Fatal Error: Unable to Load Distribution Index"
fatalErrorMessage = "A connection could not be established to our servers to download the distribution index. No local copies were available to load. <br><br>The distribution index is an essential file which provides the latest server information. The launcher is unable to start without it. Ensure you are connected to the internet and relaunch the application."
closeButton = "Close"

[js.uibinder.validateAccount]
failedMessageTitle = "Failed to Refresh Login"
failedMessage = "We were unable to refresh the login for <strong>{account}</strong>. Please select another account or login again."
failedMessageSelectAnotherAccount = "We were unable to refresh the login for <strong>{account}</strong>. Please login again."
loginButton = "Login"
selectAnotherAccountButton = "Select Another Account"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Checking for Updates..."
installNowButton = "Install Now"
checkForUpdatesButton = "Check for Updates"
